comment:
    layout: "reach, diff, flags, files"
    behavior: default
    require_changes: false  # if true: only post the comment if coverage changes
    require_base: no        # [yes :: must have a base report to post]
    require_head: yes       # [yes :: must have a head report to post]

coverage:
    range: "90..100"
    round: down
    precision: 2
    status:
        project:
            default:
                target: 100%
                threshold: 0%
                # advanced settings
                if_ci_failed: error
                informational: false
                only_pulls: false
