name: Continuous Integration

on:
    push:
        paths:
            - '**.php'
    pull_request:
        paths:
            - '**.php'
    schedule:
        - cron: '0 0 * * *'

jobs:
    tests:
        if: "!contains(github.event.head_commit.message, 'skip ci')"
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: ['7.4', '8.0']
                laravel: ['^8.0']
                stability: [prefer-lowest, prefer-stable]

        name: "CI - PHP: ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - ${{ matrix.stability }}"

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/files
                  key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, mysqli, pdo_mysql, soap, intl, gd, exif, iconv, fileinfo
                  ini-values: error_reporting=E_ALL
                  tools: composer:v2
                  coverage: pcov

            - name: Setup Problem Matches
              run: |
                  echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                  echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

            - name: Install PHP Dependencies
              run: |
                  composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
                  composer update --${{ matrix.stability }} --prefer-dist --no-interaction --ansi

            - name: PHPUnit Testing
              run: composer test:unit

            - name: Upload Code Coverage to Codecov
              uses: codecov/codecov-action@v2
              with:
                  token: ${{ secrets.CODECOV_TOKEN }}
                  file: ./tests/reports/clover.xml
                  flags: tests
                  name: codecov-umbrella
                  verbose: true
                  fail_ci_if_error: false
