name: PHPMD - PHP Mess Detector

on:
    push:
        paths:
            - '**.php'
            - 'phpmd.xml.dist'

jobs:

    phpmd:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['8.1', '8.0']
                phpmd: [^2.11]

        name: "PHPMD | PHP: ${{ matrix.php }}"

        steps:

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - name: Install Dependencies
              run: |
                composer require "phpmd/phpmd:${{ matrix.phpmd }}" --no-interaction --no-update
                composer update --prefer-stable --prefer-dist --no-interaction --ansi

            - name: Run PHPMD
              run: composer test:mess
