name: PHPStan - Code Static Analysis

on:
    push:
        paths:
            - '**.php'
            - 'phpstan.neon.dist'
    # pull_request:
    #     paths:
    #         - '**.php'
    #         - 'phpstan.neon.dist'

jobs:

    phpstan:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['8.1', '8.0']
                phpstan: [^1.0]
                symplify-rules: ['10.1.2']
                nunomaduro-larastan: [^1.0]
                ergebnis-phpstan-rules: [^1.0]

        name: "PHPStan | PHP: ${{ matrix.php }}"

        steps:

            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none

            - name: Install Dependencies
              run: |
                  composer require \
                    "phpstan/phpstan:${{ matrix.phpstan }}" \
                    "nunomaduro/larastan:${{ matrix.nunomaduro-larastan }}" \
                    "symplify/phpstan-rules:${{ matrix.symplify-rules }}" \
                    "ergebnis/phpstan-rules:${{ matrix.ergebnis-phpstan-rules }}" \
                    --no-interaction --no-update
                  composer update --prefer-stable --prefer-dist --no-interaction --ansi

            - name: Run PHPStan
              run: ./vendor/bin/phpstan analyse --error-format=github --no-progress --ansi
